---
title: "Modeling kill counts"
author: "Jonatan A. González"
date: "2025-09-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
library(lunar)
library(zoo)
library(lmtest)
library(sandwich)
library(car)
library(broom)
```


# Data

## Loading
```{r, eval = FALSE}
load("MOON.RData")
```

## Preparing factors for model
```{r, warning=FALSE}
#Gender
gender <- factor(MOON$Gender)
levels(gender) <- c("Female", "Male", "Not specified")
gender[is.na(gender)] <- "Not specified"

#Year and decade
year <- as.factor(MOON$Year)
decade <- factor(MOON$Year - MOON$Year %% 10)

#Race
race <- as.factor(MOON$Race)
levels(race) <- c(levels(race),"Not specified")
race[is.na(race)] <- "Not specified"

#Age
age.breaks <- c(0,14,64, Inf)
age <- cut(as.numeric(MOON$Age), breaks = age.breaks)
levels(age) <- c(levels(age),"Not specified")
age[is.na(age)] <- "Not specified"

#Method
method <- as.factor(MOON$Method)
levels(method) <- c(levels(method),"Not specified")
method[is.na(method)] <- "Not specified"

#Country
country <- as.factor(MOON$Country)
```

## Counts for model
```{r}
#Counts
dL <- as.POSIXct(MOON$Date, format = "%m/%d/%Y")
phase <- lunar.phase(dL, shift = 0, name = 8)
dist <- lunar.distance(dL, shift = 0, name = FALSE, strict = T)
ilu <- lunar.illumination(dL, shift = 0)

#Explanatory by day
counts1 <- as.data.frame(table(dL, gender, age))
counts1$phase <- with(counts1, lunar.phase(as.Date(dL), shift = 0, name = 8))
counts1$dist <- with(counts1, lunar.distance(as.Date(dL),
                                             shift = 0, name = T, strict = T))
counts1$ilu <- with(counts1, lunar.illumination(as.Date(dL), shift = 0))

counts1$t <-  with(counts1, julian(as.Date(dL), origin = as.Date("1960-01-01")))
counts1$month <- with(counts1, as.factor(format(as.Date(dL), "%m")))
counts1$year <- with(counts1, as.factor(format(as.Date(dL), "%Y")))
counts1$decade <- with(counts1, factor(as.numeric(as.character(year)) - as.numeric(as.character(year)) %% 10))
counts1$season <- with(counts1,
                       factor(format(as.yearqtr(as.yearmon(as.Date(dL))), "%q"), 
                              labels = c("winter", "spring", "summer", "autumn")))
counts1$tc <- scale(counts1$t, center = TRUE, scale = FALSE)
```


# Model 
```{r}
m1 <- glm(Freq ~ phase + dist + season + gender + age + ilu +
                    poly(tc, 3) + 
                    cos(2* pi * t / 365) + sin(2* pi * t / 365) +
                    cos(4* pi * t / 365) + sin(4* pi * t / 365) + 
                    cos(6* pi * t / 365) + sin(6* pi * t / 365),
                  family = "quasipoisson", data = counts1)
summary(m1)
```

## Rate Ratios

```{r}
as.data.frame(exp(coef(m1)))
CI <- exp(confint(m1)) # It could take long
CI
```


## Goodnes of fit poisson distribution

```{r}
pchisq(m1$deviance, df = m1$df.residual, lower.tail = F)
```


# DIAGNOSIS

## Nonnegative counts 
```{r}
summary(counts1$Freq)
any(counts1$Freq < 0) # debe ser FALSE
all(counts1$Freq %% 1 == 0) # TRUE si todos son enteros
```


## Autocorrelation
```{r}
m1_pois <- update(m1, family = poisson)
rp <- residuals(m1_pois, type = "pearson")
res_day <- tapply(rp, counts1$t, mean, na.rm = TRUE)

lm_res <- lm(res_day ~ 1)
dwtest(lm_res) 
```

## HAC residuals

```{r}
# Matriz HAC (Newey–West)
vc_hac <- vcovHAC(m1_pois)

# Test de coeficientes con errores HAC
coeftest(m1_pois, vcov. = vc_hac)
```


## Colineality
```{r}
vif(m1)
```

#Robustness
```{r}
# Days with no outliers (>10 homicides)
counts1_no_out <- subset(counts1, Freq <= 10)

# Reajustar el modelo
m1_no_out <- update(m1, data = counts1_no_out)
summary(m1_no_out)

# Compare moon phases coefficients
coef_out <- tidy(m1_no_out)[grep("phase", tidy(m1_no_out)$term), ]
coef_in  <- tidy(m1)[grep("phase", tidy(m1)$term), ]

list(original = coef_in, sin_outliers = coef_out)
```




